"""
# Task 2: Build the Map Graph (At Least 20 Locations)

## Implement data_fetcher.py to build a connected road-network graph for your selected country.

1. Define at least 20 cities/locations and their road connections.
2. Ensure the graph is connected so that a path exists between any two locations.
3. Use the Nominatim OpenStreetMap API to retrieve the latitude and longitude of each location.
4. Use the OSRM Routing API to retrieve actual road distances for the defined connections.
5. Construct the graph using the retrieved location and distance data.
6. Save the resulting graph to map_data.json.

## Required: map_data.json must be generated by running data_fetcher.py; do not manually create the graph data file.
"""

import requests
import json
import time

# =======================================================================
# Step 1: Define at least 20 cities/locations and their road connections
# Used AI to generate these cities and connections !
# =======================================================================

cities = [
    "Yangon",
    "Mandalay",
    "Naypyidaw",
    "Bago",
    "Mawlamyine",
    "Taunggyi",
    "Sittwe",
    "Pathein",
    "Myitkyina",
    "Lashio",
    "Hpa-an",
    "Monywa",
    "Meiktila",
    "Pyay",
    "Magway",
    "Sagaing",
    "Pakokku",
    "Dawei",
    "Myeik",
    "Bhamo",
    "Loikaw",
    "Hakha",
]

connections = {
    # Central hub - Naypyidaw connects to many cities
    "Naypyidaw": ["Yangon", "Mandalay", "Taunggyi", "Meiktila", "Pyay", "Bago"],
    # Yangon and its connections
    "Yangon": ["Bago", "Pathein", "Naypyidaw", "Mawlamyine", "Pyay"],
    # Mandalay and its connections
    "Mandalay": ["Naypyidaw", "Monywa", "Meiktila", "Sagaing", "Pyay", "Pakokku"],
    # Eastern cities
    "Taunggyi": ["Naypyidaw", "Meiktila", "Lashio", "Loikaw"],
    "Lashio": ["Taunggyi", "Mandalay", "Bhamo"],
    "Bhamo": ["Lashio", "Myitkyina"],
    "Myitkyina": ["Bhamo"],
    "Loikaw": ["Taunggyi"],
    # Southern cities
    "Mawlamyine": ["Yangon", "Bago", "Hpa-an", "Dawei"],
    "Hpa-an": ["Mawlamyine"],
    "Dawei": ["Mawlamyine", "Myeik"],
    "Myeik": ["Dawei"],
    # Western cities
    "Pathein": ["Yangon"],
    "Sittwe": ["Pyay", "Magway"],
    "Hakha": ["Sittwe"],
    # Central cities
    "Bago": ["Yangon", "Naypyidaw", "Mawlamyine"],
    "Meiktila": ["Naypyidaw", "Mandalay", "Taunggyi", "Magway"],
    "Pyay": ["Naypyidaw", "Yangon", "Mandalay", "Magway"],
    "Magway": ["Pyay", "Meiktila", "Pakokku", "Sittwe"],
    # Northern cities
    "Monywa": ["Mandalay", "Sagaing", "Pakokku"],
    "Sagaing": ["Mandalay", "Monywa"],
    "Pakokku": ["Mandalay", "Magway", "Monywa"],
}


# =======================================================================
# Step 2: check graph is connected
# =======================================================================


# =======================================================================
# Step 3: Retrive lat and lon for each location
# use OSM API to retrive lat and lon for each city in cities
# =======================================================================


def get_city_coordinates(cities_list: list[str]) -> dict:
    """
    Retrive the city's info from OSM API, store it in a dict and return it

    input:
        list of cities

    output:
        city: (lat, lon) pair
    """

    city_coordinates = {}
    url = "https://nominatim.openstreetmap.org/search"
    headers = {"User-Agent": "AI-Search-MMDT143/1.0"}

    for city in cities_list:
        time.sleep(1)
        params = {"q": city, "format": "json"}
        try:
            print("fSearching for {city}")
            r = requests.get(url, params=params, headers=headers, timeout=10)
            print(f"Status  : {r.status_code}")
            print(f"URL     : {r.url}")
            r.raise_for_status()
            data = r.json()

            if data:
                lat = data[0]["lat"]
                lon = data[0]["lon"]
                city_coordinates[city] = (lat, lon)

        except requests.RequestException as e:
            print(f"Error fetching {city}: {e}")

    return city_coordinates


# =======================================================================
# Step 4: Using the OSRM Routing API to retrieve actual road distances for the defined connections
# Used AI to help generate part of this function !
# =======================================================================
def get_connected_pairs(connections):
    """
    Given connections : "cityA" :["townA", "townB"]
    return [(cityA, townA), (cityA, townB)]
    """
    # Make all unique pairs of connected cities
    connected_pairs = set()
    for city, neighbors in connections.items():
        for neighbor in neighbors:
            pair = tuple(sorted([city, neighbor]))
            connected_pairs.add(pair)


def get_connected_pairs_distances(city_coordinates, connected_pairs):
    """
    Get actual road distances between connected cities using OSRM API.
    Returns a dictionary with distances between city pairs.
    """
    distances = {}

    print("\nFetching road distances between connected cities...")

    total_pairs = len(connected_pairs)
    current = 0

    for city1, city2 in connected_pairs:
        current += 1
        # Skip if coordinates are missing
        if city_coordinates.get(city1) is None or city_coordinates.get(city2) is None:
            print(f"⚠ Skipping {city1} - {city2} (missing coordinates)")
            continue

        lat1, lon1 = city_coordinates[city1]
        lat2, lon2 = city_coordinates[city2]

        # OSRM API URL for driving distance
        url = f"http://router.project-osrm.org/route/v1/driving/{lon1},{lat1};{lon2},{lat2}"
        params = {"overview": "false"}  # We only need distance, not full route

        try:
            r = requests.get(url, params=params)
            r.raise_for_status()
            data = r.json()

            if data.get("code") == "Ok" and data.get("routes"):
                distance_meters = data["routes"][0]["distance"]
                distance_km = round(distance_meters / 1000, 1)  # Convert to km

                # Store distance in both directions (undirected graph)
                key = f"{city1}-{city2}"
                distances[key] = distance_km
                print(
                    f"✓ [{current}/{total_pairs}] {city1} - {city2}: {distance_km} km"
                )
            else:
                print(
                    f"✗ [{current}/{total_pairs}] No route found for {city1} - {city2}"
                )
                distances[f"{city1}-{city2}"] = None

        except Exception as e:
            print(f"✗ [{current}/{total_pairs}] Error fetching {city1} - {city2}: {e}")
            distances[f"{city1}-{city2}"] = None

    return distances


# =======================================================================
# Step 5:
# =======================================================================


def build_and_save_graph(
    cities, connections, city_coordinates, connected_pairs_distances
):
    """
    Construct the graph and save to map_data.json
    """
    graph_data = {
        "cities": cities,
        "coordinates": city_coordinates,
        "connections": connections,
        "distances": connected_pairs_distances,
    }

    # Save to JSON file
    with open("map_data.json", "w") as f:
        json.dump(graph_data, f, indent=2)

    print("\n✅ Graph data saved to map_data.json")
    print(f"Total cities: {len(cities)}")
    print(
        f"Total connections with distances: {len([d for d in connected_pairs_distances.values() if d is not None])}"
    )


if __name__ == "__main__":
    cities_coordinates = get_city_coordinates(cities)
    connected_pairs = get_connected_pairs(connections)
    connected_pairs_distances = get_connected_pairs_distances(
        cities_coordinates, connected_pairs
    )
    build_and_save_graph(
        cities, connections, cities_coordinates, connected_pairs_distances
    )
